name: CI GaragePhp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4" # la version de php que vous utilisez
          extensions: pdo_mysql, # Ajoute les extensions nécessaires
          tools: composer # installe composer

      - name: Installation des dependances composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Execution des tests PHPUnit
        run: vendor/bin/phpunit # Assurez vous que PHPUNIT est configuré
